### ISSUE TITLE
Conditional comments not minified

### ISSUE THREAD

**Issue by hroma** [afbora/kirby-minify-html#1]
On my side everything is working as expected. I only had a small piece of html (conditional comment) that wasn't minified. 

To reproduce the "issue", place the following somewhere in your html:
`<!--[if lt IE 9]>`
`  <div class="browserUpdate">`
`    <p>Bro, don't you think it's time to upgrade to a real browser? </p>`
`    <p><a href="http://browsehappy.com/" target="_blank">UPDATE NOW</a> </p>`
`  </div>`
`<![endif]-->`

RESULT (after minification): 
`<!--[if lt IE 9]>`
`  <div class="browserUpdate">`
`    <p>Bro, don't you think it's time to upgrade to a real browser? </p>`
`    <p><a href="http://browsehappy.com/" target="_blank">UPDATE NOW</a> </p>`
`  </div>`
`<![endif]-->`

EXPECTED (after minification):
 `<!--[if lt IE 9]><div class="browserUpdate"><p>Bro, don't you think it's time to upgrade to a real browser? </p><p><a href="http://browsehappy.com/" target="_blank">UPDATE NOW</a></p></div><![endif]-->`

Hope it helps you make your plugin even BETTER :-)

**Comment by afbora** [comment]
Thanks for feedback.  This repository uses `voku/HtmlMin` library and that doesn't seem possible due to following description by maintainer on `voku/HtmlMin` repository:

> Protected HTML (inline css / inline js / conditional comments) are still protected, no matter what settings you use.

**Ref**: https://github.com/voku/HtmlMin#options
