### ISSUE TITLE
v4 Compatibility

### ISSUE THREAD

**Issue by animaux** [afbora/kirby-minify-html#10]
Will there be a compatible version for Kirby v4?

**Comment by afbora** [comment]
Sure, I need to check out.

**Comment by afbora** [comment]
Did you test it in v4 and do you get any errors?

**Comment by animaux** [comment]
> Did you test it in v4 and do you get any errors?

Just starting to do so, looking fine so far, thanks!

**Comment by afbora** [comment]
Great! Let me know if you have any issue.
