### ISSUE TITLE
Allow options of type array

### ISSUE THREAD

**Issue by timnarr** [afbora/kirby-minify-html#4]
Hi Ahmet,

I want to use the `doMakeSameDomainsLinksRelative ` option and pass an array with domains to the minifier, like this:
`'doMakeSameDomainsLinksRelative' => ['https://example.com'],` 

But using this option will lead to an TypeError:
"voku\helper\HtmlMin::doMakeSameDomainsLinksRelative(): Argument #1 ($localDomains) must be of type array, bool given ..."

What do you think? Could this be customized?

Thanks for your time and the great plugin.
Tim

**Comment by afbora** [comment]
Fixed on v1.4.0 release. Could you test please?

https://github.com/afbora/kirby-minify-html/releases/tag/1.4.0

**Comment by timnarr** [comment]
Thank you for your quick help! The new version works fine for me :)
