### ISSUE TITLE
Remove comments

### ISSUE THREAD

**Issue by Afplaktape** [afbora/kirby-minify-html#5]
Hi,

Minifying works but unfortunately my comments are removed even though I added this to my config.php:

```
  'afbora.kirby-minify-html.enabled' => true,
  'afbora.kirby-minify-html.options' => [
      'doOptimizeViaHtmlDomParser' => true,
      'doRemoveComments' => false,
  ],
```

Am I missing something?

**Comment by afbora** [comment]
I can't reproduce the issue. Work as expected.
Can you share your template code with comments?

**Comment by Afplaktape** [comment]
Sorry my bad I missed a comma somewhere -_-
