### ISSUE TITLE
Collision with `getkirby/layouts` plugin

### ISSUE THREAD

**Issue by S1SYPHOS** [afbora/kirby-minify-html#6]
.. and I can't figure out why! What could possible pitfalls be? On many other websites, I install it and it just worksTM - I tried `var_dump`ing from inside the plugin, nothing - I don't even know if it's loaded - and if not, why ..

I appreciate all pointers,

cheers
S1SYPHOS

**Comment by afbora** [comment]
I'm not sure how can I help you. I need more information, setup, details etc..

**Comment by S1SYPHOS** [comment]
I guess it collides with [`getkirby/layouts`](https://github.com/getkirby/layouts) plugin, which also extends the core component `template`!

**Comment by afbora** [comment]
Good point. I think it's difficult that using both component same time.

**Comment by S1SYPHOS** [comment]
I guess at this point, there's no way of using both except adding support for one another .. and building some kind of HTML minification / your plugin into the core would violate Kirby's premise of maximum user freedom BUT on the other hand, making minification 'pluggable' and using your setup as default inside `Template` would be great IMHO

**Comment by afbora** [comment]
Definitely you're right! We need more hooks to more pluggable For ex: `page.render:before`, `page.render:after` or something like that.

**Comment by afbora** [comment]
May be @bastianallgeier give us an idea about that 🙏

**Comment by S1SYPHOS** [comment]
.. and I guess it would not even be that much work (yeah, easy coming from me, sorry), but I imagine it's not _that much_ - which makes it more likely to be implemented which in turn makes me very happy right now 😃

**Comment by afbora** [comment]
For now I've added an idea about that https://kirby.nolt.io/419
